import re

class ConfidenceEvaluator:
    @staticmethod
    def calculate_score(state):
        """
        Calculates a confidence score based on:
        - Schema alignment
        - Retry count
        - Query complexity
        """
        score = 100
        
        # 1. Deduct for retries (higher retries = lower initial confidence)
        score -= (state.get('retry_count', 0) * 15)
        
        # 2. Deduct for complexity (joins, subqueries)
        sql = state.get('sql', '').lower()
        joins = len(re.findall(r'\bjoin\b', sql))
        subqueries = len(re.findall(r'\(.*select.*\)', sql))
        
        score -= (joins * 5)
        score -= (subqueries * 10)
        
        # 3. Check for specific markers (if SQL was generated by LLM, it's generally good but needs verification)
        if not sql:
            score = 0
        elif "select *" in sql: # Select * is slightly less "confident" in terms of specific intent match
            score -= 5
            
        # 4. Error state
        if state.get('error'):
            score = 20 # Low confidence if there was an error
            
        # Ensure range
        score = max(0, min(100, score))
        
        level = "High"
        if score < 70:
            level = "Low"
        elif score < 90:
            level = "Medium"
            
        return score, level
